// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TYPE YOUR API KEY HERE',
    appId: '1:320070681555:web:6e38b355ac1dc2dd576526',
    messagingSenderId: '320070681555',
    projectId: 'fitness-cfbac',
    authDomain: 'fitness-cfbac.firebaseapp.com',
    storageBucket: 'fitness-cfbac.firebasestorage.app',
    measurementId: 'G-0R9N87K4G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TYPE YOUR API KEY HERE',
    appId: '1:320070681555:android:06ad1099b5feb396576526',
    messagingSenderId: '320070681555',
    projectId: 'fitness-cfbac',
    storageBucket: 'fitness-cfbac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TYPE YOUR API KEY HERE',
    appId: '1:320070681555:ios:d20af0c896333c78576526',
    messagingSenderId: '320070681555',
    projectId: 'fitness-cfbac',
    storageBucket: 'fitness-cfbac.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TYPE YOUR API KEY HERE',
    appId: '1:320070681555:ios:d20af0c896333c78576526',
    messagingSenderId: '320070681555',
    projectId: 'fitness-cfbac',
    storageBucket: 'fitness-cfbac.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TYPE YOUR API KEY HERE',
    appId: '1:320070681555:web:36c0c8a2d5b4c74b576526',
    messagingSenderId: '320070681555',
    projectId: 'fitness-cfbac',
    authDomain: 'fitness-cfbac.firebaseapp.com',
    storageBucket: 'fitness-cfbac.firebasestorage.app',
    measurementId: 'G-4E72KGLG9J',
  );
}
